name: mtk_tsm
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - _tflow_select=2.3.0
  - abseil-cpp=20211102.0
  - absl-py=2.1.0
  - aiohappyeyeballs=2.4.0
  - aiohttp=3.10.5
  - aiosignal=1.2.0
  - astunparse=1.6.3
  - async-timeout=4.0.3
  - attrs=24.2.0
  - blas=1.0
  - blinker=1.6.2
  - bottleneck=1.3.5
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2024.12.31
  - certifi=2024.8.30
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - cryptography=38.0.1
  - cudatoolkit=11.3.1
  - decorator=5.1.1
  - ffmpeg=4.2.2
  - flatbuffers=24.3.25
  - freetype=2.12.1
  - frozenlist=1.4.0
  - future=0.18.2
  - gast=0.4.0
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - google-pasta=0.2.0
  - grpc-cpp=1.46.1
  - h5py=3.11.0
  - hdf5=1.12.1
  - icu=58.2
  - idna=3.4
  - imageio=2.35.1
  - imageio-ffmpeg=0.5.1
  - intel-openmp=2021.4.0
  - jpeg=9e
  - keras-preprocessing=1.1.2
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.12
  - ld_impl_linux-64=2.38
  - leptonica=1.80.0
  - lerc=3.0
  - libarchive=3.5.2
  - libcurl=8.2.1
  - libdeflate=1.8
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.3
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.2
  - libnghttp2=1.52.0
  - libopus=1.3.1
  - libpng=1.6.37
  - libprotobuf=3.20.3
  - libssh2=1.10.0
  - libstdcxx-ng=11.2.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libuv=1.40.0
  - libvpx=1.7.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - moviepy=1.0.3
  - multidict=6.0.4
  - ncurses=6.3
  - nettle=3.7.3
  - ninja-base=1.10.2
  - numexpr=2.8.3
  - oauthlib=3.2.2
  - openh264=2.1.1
  - openjpeg=2.4.0
  - openssl=1.1.1w
  - opt_einsum=3.3.0
  - packaging=21.3
  - pillow=9.2.0
  - platformdirs=3.10.0
  - pooch=1.7.0
  - proglog=0.1.9
  - pycparser=2.21
  - pyjwt=2.8.0
  - pyopenssl=22.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.13
  - python-dateutil=2.8.2
  - python-flatbuffers=24.3.25
  - pytorch-mutex=1.0
  - pytz=2022.1
  - re2=2022.04.01
  - readline=8.2
  - requests=2.28.1
  - requests-oauthlib=2.0.0
  - rsa=4.7.2
  - six=1.16.0
  - snappy=1.2.1
  - sqlite=3.39.3
  - tensorboard-plugin-wit=1.8.1
  - termcolor=2.1.0
  - tesseract=4.1.1
  - tk=8.6.12
  - tqdm=4.66.5
  - urllib3=1.26.12
  - werkzeug=3.0.3
  - wheel=0.37.1
  - wrapt=1.14.1
  - x264=1!157.20191217
  - xz=5.2.6
  - yarl=1.11.0
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - asttokens==3.0.0
      - awscli==1.35.10
      - backcall==0.2.0
      - beautifulsoup4==4.13.4
      - bleach==6.1.0
      - boto3==1.35.44
      - botocore==1.35.44
      - cachetools==5.4.0
      - cloudpickle==3.1.1
      - coloredlogs==15.0.1
      - contourpy==1.1.1
      - cycler==0.12.1
      - defusedxml==0.7.1
      - dm-tree==0.1.8
      - docopt==0.6.2
      - docutils==0.16
      - einops==0.8.0
      - et-xmlfile==1.1.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.15.4
      - fonttools==4.53.1
      - fsspec==2024.6.1
      - fvcore==0.1.5.post20221221
      - google-auth==2.33.0
      - google-auth-oauthlib==1.0.0
      - grpcio==1.65.4
      - huggingface-hub==0.26.2
      - humanfriendly==10.0
      - importlib-metadata==8.2.0
      - importlib-resources==6.4.2
      - iopath==0.1.10
      - ipython==8.12.3
      - jedi==0.19.2
      - jinja2==3.1.4
      - jmespath==1.0.1
      - joblib==1.4.2
      - jsonschema==4.23.0
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.3
      - jupyter-core==5.8.1
      - jupyterlab-pygments==0.3.0
      - keras==2.13.1
      - kiwisolver==1.4.5
      - libclang==18.1.1
      - markdown==3.6
      - markupsafe==2.1.5
      - matplotlib==3.7.5
      - matplotlib-inline==0.1.7
      - mistune==3.1.3
      - mpmath==1.3.0
      - nbclient==0.10.1
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - networkx==3.1
      - ninja==1.11.1
      - numpy==1.24.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.20
      - nvidia-nvtx-cu12==12.1.105
      - onnx==1.17.0
      - onnx-tf==1.10.0
      - onnxruntime==1.19.2
      - onnxruntime-gpu==1.19.2
      - opencv-python==4.10.0.84
      - openpyxl==3.1.5
      - pandas==2.0.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pip==25.0.1
      - pipreqs==0.5.0
      - pkgutil-resolve-name==1.3.10
      - portalocker==3.0.0
      - prompt-toolkit==3.0.51
      - protobuf==3.20.3
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyasn1==0.6.0
      - pyasn1-modules==0.4.0
      - pygments==2.19.2
      - pytesseract==0.3.13
      - pyyaml==6.0.2
      - pyzmq==27.0.0
      - referencing==0.35.1
      - rpds-py==0.20.1
      - s3transfer==0.10.3
      - safetensors==0.4.5
      - scikit-learn==1.3.2
      - scipy==1.10.1
      - seaborn==0.13.2
      - setuptools==59.5.0
      - soupsieve==2.7
      - stack-data==0.6.3
      - svgwrite==1.4.3
      - sympy==1.13.2
      - tabulate==0.9.0
      - tensorboard==2.13.0
      - tensorboard-data-server==0.7.2
      - tensorboardx==2.6.2.2
      - tensorflow==2.10.0
      - tensorflow-addons==0.21.0
      - tensorflow-estimator==2.13.0
      - tensorflow-io-gcs-filesystem==0.34.0
      - tensorflow-probability==0.21.0
      - tf2onnx==1.16.1
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - timm==1.0.11
      - tinycss2==1.2.1
      - torch==2.4.0
      - torchinfo==1.8.0
      - torchsummary==1.5.1
      - torchvision==0.19.0
      - tornado==6.4.2
      - traitlets==5.14.3
      - tree==0.2.4
      - triton==3.0.0
      - typeguard==2.13.3
      - typing-extensions==4.5.0
      - tzdata==2024.2
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - yacs==0.1.8
      - yarg==0.1.9
      - zipp==3.20.0
